<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CoConnect.Messaging</AssemblyName>
    <RootNamespace>CoConnect.Messaging</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoConnect.Persistence\CoConnect.Persistence.csproj" />
    <ProjectReference Include="..\SimpleBus\SimpleBus.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>

</Project>
